os: linux
dist: bionic
language: node_js
node_js:
- '10'
- '12'
cache:
  yarn: true
  directories:
  - node_modules
before_install:
- curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.19.1
- export PATH="$HOME/.yarn/bin:$PATH"
script:
- make build
- make test
deploy:
  edge: true
  provider: npm
  email: sharevb@gmail.com
  cleanup: false
  on:
    branch: master
    tags: true
    repo: outilslibre/composeverter
  api_key:
    secure: QkxH7Hb2IclFyWC9plMyf8oLGLK6V9X7j9ig+Cc1NH/kWLVt6mXRDl52WYC1+jojOfqVise7z8Fp8IH9ftAIC3yAuovAOdq3OnJYKh3eW4U07LwodknLSYOABbeQGMi96Mgpb3SNmsFfmu90vEWfPdUWFBnB1e4GHnYlIcJCi0ShlTKtrP3SGSXH0I/f4k557/ZEEX2p3gEEtbiHUqGS/vfEVU4EwwNqw9TkiVsyw7Cu0Id9CeR26Xizp2CWTUvXs4ZAqBV8yEDn/QNNwI5sYN+ASCchkKwRldBw2mEbldeUzQUaCq6medUxrv8qHh+50lWdhS7ARKipxzOPEUjRub8r5S3jLEEdP0GvWYgs/lcn069LbxM+x16NRaSQjUkeFWZa2PVLP/b0yXoV3bALmCxITqIV9ajD1SED9RTWXzurJ3/ngSwA1P36M9i7nTB1hPznlq+DbYwcEjBB+uJUVyu+v7mopF7kFysi74AUT0HVXhPn9beUzVoMaF535E9ow6DCC6cJombC1J9c5psrBBbLED8BwHLqlMXkYRkN5yGN9Sr+zivWrKmQm3ZhvCXsg/0GSvLUR1vtxwWTn0SC3QoSHh8kHg00b/O34SAKwsOOXfZG1OPZqR2zyw+2NfU06N2DCwD2iJkVmwrvGdnMvv9CHd1A6C6g0S2y39xeFgc=
